services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - WEAVIATE_URL=http://localhost:8091
      - WEAVIATE_API_KEYS=secret
      - WEAVIATE_USERS=admin
